#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -s "$HOME/.profile" ]]; then
  source "$HOME/.profile"
fi

# Java aliases
alias use-java-7='export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_25.jdk/Contents/Home"; export PATH=$JAVA_HOME/bin:$PATH'
alias use-java-8='export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home"; export PATH=$JAVA_HOME/bin:$PATH'

# Default Java
use-java-8

# local bin to PATH
export PATH="$HOME/bin:$PATH"

# mysql
export PATH="/usr/local/mysql/bin:$PATH"

# maven
MAVEN_OPTS="-Dmaven.artifact.threads=15 -Xmx512M -XX:PermSize=256M -XX:MaxPermSize=512M"

# python
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

# sbt
export SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

# go
GOPATH=$HOME/go
export GOBIN="$GOPATH/bin"
export PATH="$GOBIN:$PATH"

# haskell
## cabal (haskell build tool)
export PATH=~/.cabal/bin:$PATH
## stack
export PATH="/Users/victor/Work/Apps/stack:$PATH"

# LaTeX
export PATH="/usr/local/texlive/2016basic/bin/universal-darwin/:$PATH"

# RVM (Ruby Version Manager)
function rvm() {
  if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    unset -f rvm
    source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
    rvm $@
  else
    echo "rvm not found, see ~/.zshenv"
  fi
}

# NVM (NodeJs Version Manager)
function nvm() {
  nvm_path=""
  # Load manually installed NVM into the shell session.
  if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
    nvm_path="$HOME/.nvm/nvm.sh"
  # Load package manager installed NVM into the shell session.
  elif (( $+commands[brew] )) && [[ -d "$(brew --prefix nvm 2>/dev/null)" ]]; then
    nvm_path=$(brew --prefix nvm)/nvm.sh
  fi
  if [[ "$nvm_path" == "" ]]; then
    echo "nvm not found, see ~/.zshenv"
  else
    source $nvm_path
    unset nvm
    nvm $@
  fi
}

# psql
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"

# projects
alias tackler='cd ~/Work/mine/projects/tackler'

# Kubernetes and GCloud
alias k='kubectl'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/victor/Work/Apps/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/victor/Work/Apps/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/victor/Work/Apps/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/victor/Work/Apps/google-cloud-sdk/completion.zsh.inc'; fi

